#page title
page_title: Coconotes # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
# ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

#appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
#presskit_download_link: https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.

app_name: Coconotes # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Instant braindumps to your Gmail

enable_smart_app_banner: false # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Roman Six
your_link: https://coconotes.romansix.org
your_city: San Francisco
email_address: coconotes@romansix.org
#facebook_username:
#instagram_username: ebaehr
#twitter_username: ebaehr
#github_username: emilbaehr
#youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Fast braindumps
    description: Send ideas and todos instantly. Avoid attention residue and distractions from your current task.
    fontawesome_icon_name: fas fa-brain

  - title: Tagging
    description: Categorize your notes with one tap. Use Gmail filters to automatically categorize them.
    fontawesome_icon_name: fas fa-hashtag

  - title: Integrates with Gmail
    description: Notes are emails, so you can use the power of Gmail to manage them. Filter them, group them, star or snooze them for later.
    fontawesome_icon_name: fab fa-google

  - title: Favorite recipients
    description: Send notes to your commonly used destinations with one tap by creating a list of email recipients, and optionally tags.
    fontawesome_icon_name: fas fa-user-friends

  - title: Photo attachments
    description: It only takes a couple taps to include a photo with your note - you can include a lot of detail quickly this way.
    fontawesome_icon_name: fas fa-camera-retro

  - title: Offline queueing
    description: In airplane mode? Queue your notes and they will be automatically sent when you are back online.
    fontawesome_icon_name: fas fa-plane

  - title: Works with your tools
    description: Coconotes integrates well with most task management systems via email integration - such as Todoist, TickTick, Remember the Milk. Or use Zapier/Integromat to forward tasks from your Gmail.
    fontawesome_icon_name: fas fa-plug

  - title: And more on the way...
    description: iOS app, calendar integration...
    fontawesome_icon_name: fas fa-magic


# Theme Settings
topbar_color: '#000000'
topbar_transparency: 0.1
topbar_title_color: '#ffffff'

cover_image: assets/coconut.jpg # Replace with alternative image path or image URL.
cover_overlay_color: '#363b3d'
cover_overlay_transparency: 0.8

device_color: pixel # Set to: blue, black, yellow, coral or white.

body_background_color: '#ffffff'

link_color: '#1d63ea'

app_title_color: '#ffffff'
app_price_color: '#ffffff'
app_description_color: '#ffffff'

feature_title_color: '#000000'
feature_text_color: '#666666'

feature_icons_foreground_color: '#1d63ea'
feature_icons_background_color: '#e6e6e6'

social_icons_foreground_color: '#666666'
social_icons_background_color: '#e6e6e6'

footer_text_color: '#666666'

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
